### ISSUE TITLE
queueListener.done is not a function

### ISSUE THREAD

**Issue by jbrozena22** [dei79/node-azure-queue-client#1]
Hi, thanks for this awesome and easy to use package!

I'm getting the error 

`queueListener.done is not a function`

How can I override the done function so there is actually something to run there so as to avoid this error? Or is there something I can return other than queueListener.done() to avoid this entirely?

Thank you.

**Comment by dei79** [comment]
Hi, I added the missing done function in the latest release. Normally done is doing nothing then returning a promise. So just return a promise and work with promises to process async calls.

**Comment by jbrozena22** [comment]
Thank you!
